### PR TITLE
Added .gitignore file

### PR DESCRIPTION
**Pull request by mattwatson**
Have also used git rm \* --cached to remove all the files that shouldn't be in source control.
Git won't add anything that shouldn't be there

### CODE REVIEW

**Comment by DaveEmmerson** [comment]
Ok... so this is the same as the change I made, except your .gitignore is pinched from a different place than mine I guess.

Should I try to merge yours in or leave it as mine and reject this?

**Comment by mattwatson** [comment]
I literally went to the settings for the repository in github client and
checked a checkbox :)

I'll take a look at it, merge it in, and resubmit if necessary.

Matt

**Comment by DaveEmmerson** [comment]
Can I give you access to change things yourself somehow?

I can't see a way... but I think I remember you saying it was possible?

Maybe I should just google it!

**Comment by DaveEmmerson** [comment]
Oh. I may have done it already. Adding someone as a collaborator sounds like it does it perhaps...

**Pull request merged**
